import { sqliteTable, text, integer, uniqueIndex } from "drizzle-orm/sqlite-core";

// one branch = one cabang (a team/group counts as its own branch).
// inactive branches stay for history; their members go read-only.
export const branches = sqliteTable("branches", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  createdAt: integer("created_at").notNull(),
});

// accounts. superadmin owns every branch and has no branch of its own;
// admin and presenter always belong to exactly one branch (db check).
export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  username: text("username").notNull().unique(),
  passwordHash: text("password_hash").notNull(),
  role: text("role", { enum: ["superadmin", "admin", "presenter"] })
    .notNull()
    .default("presenter"),
  branchId: integer("branch_id").references(() => branches.id),
  createdAt: integer("created_at").notNull(),
});

// one row per branch: that branch's own calculation values, superadmin-editable.
export const settings = sqliteTable("settings", {
  branchId: integer("branch_id")
    .primaryKey()
    .references(() => branches.id),
  closingPrice: integer("closing_price").notNull(),
  bopPercent: integer("bop_percent").notNull(),
  souvenirUnitPrice: integer("souvenir_unit_price").notNull(),
  souvenirPercent: integer("souvenir_percent").notNull(),
  harianDefault: integer("harian_default").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// one row = one presenter's daily closing recap. inputs, settings, and
// computed values are snapshotted so later settings changes never rewrite it.
// branch_id is snapshotted too: moving a presenter never moves old entries.
// client_id is generated by the app once per closing, so a resend after a lost
// response finds the row it already created instead of adding a second one.
export const salesEntries = sqliteTable("sales_entries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  clientId: text("client_id"),
  presenterId: integer("presenter_id")
    .notNull()
    .references(() => users.id),
  branchId: integer("branch_id")
    .notNull()
    .references(() => branches.id),
  entryDate: text("entry_date").notNull(), // iso yyyy-mm-dd
  status: text("status", { enum: ["pending", "approved"] })
    .notNull()
    .default("approved"),
  closingCount: integer("closing_count").notNull(),
  bopInput: integer("bop_input").notNull(),
  audienceCount: integer("audience_count").notNull(),
  harian: integer("harian").notNull(),
  closingPriceUsed: integer("closing_price_used"),
  bopPercentUsed: integer("bop_percent_used"),
  souvenirUnitPriceUsed: integer("souvenir_unit_price_used"),
  souvenirPercentUsed: integer("souvenir_percent_used"),
  closingTotal: integer("closing_total").notNull(),
  bopValue: integer("bop_value").notNull(),
  souvenirValue: integer("souvenir_value").notNull(),
  takeHome: integer("take_home").notNull(),
  approvedAt: integer("approved_at"),
  approvedBy: integer("approved_by").references(() => users.id),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
  clientIdUnique: uniqueIndex("sales_entries_client_id_unique").on(t.clientId),
}));

export type Branch = typeof branches.$inferSelect;
export type User = typeof users.$inferSelect;
export type Settings = typeof settings.$inferSelect;
export type SalesEntry = typeof salesEntries.$inferSelect;
